export const sampleProducts = [
  {
    id: 1,
    title: "Dharma",
    description: "Experience crystal-clear audio with our premium wireless headphones featuring advanced noise cancellation technology, 30-hour battery life, and premium comfort padding. Perfect for music enthusiasts, professionals, and anyone who values superior sound quality.",
    price: 12999,
    originalPrice: 15999,
    category: "Bio-Fertilizers",
    image: "https://i.pinimg.com/736x/75/58/80/755880fbdd1f6551bc7c2032af8c50a5.jpg",
    featured: true,
    inStock: true,
    rating: 4.5,
    reviews: 128
  },
  {
    id: 2,
    title: "Bheem",
    description: "Sustainably crafted from 100% organic cotton, this comfortable t-shirt offers breathable fabric and a perfect fit. Available in multiple colors and sizes, it's ideal for everyday wear and environmentally conscious consumers.",
    price: 1299,
    originalPrice: 1599,
    category: "Bio-Fungicides",
    image: "/placeholder.svg?height=400&width=400&text=Cotton+T-Shirt",
    featured: false,
    inStock: true,
    rating: 4.2,
    reviews: 89
  },
  {
    id: 3,
    title: "Varna",
    description: "Advanced fitness tracking watch with comprehensive health monitoring, GPS navigation, smartphone connectivity, and 7-day battery life. Track your workouts, monitor your health, and stay connected on the go.",
    price: 8999,
    originalPrice: 11999,
    category: "Bio-Nematicides",
    image: "/placeholder.svg?height=400&width=400&text=Smart+Watch",
    featured: true,
    inStock: true,
    rating: 4.7,
    reviews: 256
  },
  {
    id: 4,
    title: "Bhishma",
    description: "Handcrafted from genuine leather, this spacious messenger bag combines style and functionality. Perfect for work, travel, or daily use with multiple compartments and durable construction that ages beautifully.",
    price: 4999,
    originalPrice: 6999,
    category: "Bio-Insecticides",
    image: "/placeholder.svg?height=400&width=400&text=Leather+Bag",
    featured: false,
    inStock: true,
    rating: 4.4,
    reviews: 67
  },
  {
    id: 5,
    title: "Dharma",
    description: "Elegant set of 4 ceramic coffee mugs with beautiful glazed finish and ergonomic design. Perfect for your morning coffee routine, these mugs are dishwasher safe and designed to retain heat longer.",
    price: 2499,
    originalPrice: 2999,
    category: "Bio-Insecticides",
    image: "/placeholder.svg?height=400&width=400&text=Coffee+Mugs",
    featured: false,
    inStock: true,
    rating: 4.1,
    reviews: 43
  },
  {
    id: 6,
    title: "Varna",
    description: "Non-slip premium yoga mat made from eco-friendly TPE material. Provides excellent grip and cushioning for all types of yoga and fitness exercises. Lightweight, durable, and easy to clean.",
    price: 3499,
    originalPrice: 4499,
    category: "Bio-Nematicides",
    image: "/placeholder.svg?height=400&width=400&text=Yoga+Mat",
    featured: true,
    inStock: true,
    rating: 4.6,
    reviews: 134
  },
  {
    id: 7,
    title: "Bhisma",
    description: "Fast wireless charging pad compatible with all Qi-enabled devices. Features LED indicator, overcharge protection, and sleek design that complements any workspace or bedside table.",
    price: 2999,
    originalPrice: 3999,
    category: "Bio-Fertilizers",
    image: "/placeholder.svg?height=400&width=400&text=Wireless+Charger",
    featured: false,
    inStock: true,
    rating: 4.3,
    reviews: 92
  },
 
];
